export const COACHING_AI_FEATURES = [
  {
    key: 'ai_lecture_processing',
    label: 'AI Lecture Processing',
    description: 'Auto-transcribes lectures, translates them, and enriches notes from images/handwriting.',
    icon: 'Video',
    defaultEnabled: true,
    category: 'teacher',
  },
  {
    key: 'ai_doubt_solver',
    label: 'AI Doubt Solver',
    description: 'Instantly answers student doubts, including from photos of handwritten questions.',
    icon: 'MessageSquare',
    defaultEnabled: true,
    category: 'student',
  },
  {
    key: 'ai_learning_assistant',
    label: 'AI Learning Assistant',
    description: 'Acts as a personal AI tutor — explains concepts and builds study plans.',
    icon: 'Sparkles',
    defaultEnabled: true,
    category: 'student',
  },
  {
    key: 'ai_student_insights',
    label: 'AI Student Insights',
    description: 'Surfaces AI-driven performance analytics and progress trends per student.',
    icon: 'Sparkles',
    defaultEnabled: true,
    category: 'student',
  },
  {
    key: 'ai_assessment_grading',
    label: 'AI Assessment & Grading',
    description: 'AI-assisted grading of mock tests, including handwritten answer sheets.',
    icon: 'Scan',
    defaultEnabled: true,
    category: 'both',
  },
  {
    key: 'ai_content_generation',
    label: 'AI Content Generation',
    description: 'Auto-generates notes, question sets, and study material from source content.',
    icon: 'FileText',
    defaultEnabled: true,
    category: 'teacher',
  },
  {
    key: 'ai_battle_arena',
    label: 'AI Battle Arena',
    description: 'AI-powered competitive quiz/battle mode between students.',
    icon: 'ClipboardList',
    defaultEnabled: true,
    category: 'both',
  },
];
