import React, { useEffect, useState } from 'react';
import { Trophy, Loader2 } from 'lucide-react';
import * as competitiveApi from '@/lib/api/competitive';
import type { StudentCompetitiveSubject } from '@/lib/api/competitive';
import { handleApiError } from '@/lib/school/errorHandler';

export default function CompetitivePrep() {
  const [subjects, setSubjects] = useState<StudentCompetitiveSubject[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    (async () => {
      try {
        setSubjects(await competitiveApi.listCompetitiveSubjectsForStudent());
      } catch (err) {
        handleApiError(err, 'Failed to load competitive prep subjects');
      } finally {
        setLoading(false);
      }
    })();
  }, []);

  if (loading) return <div className="p-10 flex justify-center"><Loader2 className="w-6 h-6 animate-spin text-indigo-500" /></div>;

  return (
    <div className="p-4 sm:p-6 lg:p-8 w-full space-y-6">
      <div className="flex items-center gap-3">
        <div className="w-12 h-12 rounded-2xl bg-indigo-600 flex items-center justify-center shadow-lg shadow-indigo-500/20">
          <Trophy className="w-6 h-6 text-white" />
        </div>
        <div>
          <h1 className="text-2xl font-black text-slate-900">Competitive Exam Prep</h1>
          <p className="text-slate-500 text-sm">JEE/NEET-style practice for your class, generated by your teacher.</p>
        </div>
      </div>

      {subjects.length === 0 ? (
        <div className="bg-white rounded-2xl border border-dashed border-slate-200 p-10 text-center text-slate-400">
          Nothing here yet — your class doesn't have a competitive subject set up, or your teacher hasn't published any practice questions yet.
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {subjects.map((s) => (
            <div key={s.id} className="bg-white rounded-2xl border border-slate-200 p-5">
              <p className="font-bold text-slate-800">{s.display_name || s.master_subject_name}</p>
              <p className="text-xs text-slate-400 mb-3">{s.master_subject_name} · {s.exam_name}</p>
              <p className="text-sm text-slate-400">No published practice questions yet — check back soon.</p>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
